-- restart bd
USE DB_ETABLE;
DROP TABLE IF EXISTS TBTIPOUSUARIOPERMISO;
DROP TABLE IF EXISTS TBESTADOPROGRAMACION;
DROP TABLE IF EXISTS tbprogramacionmesa;
DROP TABLE IF EXISTS tbreservacion;
DROP TABLE IF EXISTS TBESTADORESERVACION;
DROP TABLE IF EXISTS TBCLIENTES;
DROP TABLE IF EXISTS TBUSUARIOS;
DROP TABLE IF EXISTS TBTIPOUSUARIO;
DROP TABLE IF EXISTS TBCONFIGURACIONSISTEMA;
DROP TABLE IF EXISTS TBPERMISOS;
DROP TABLE IF EXISTS TBMESA;
DROP TABLE IF EXISTS TBESTADOMESA;
DROP TABLE IF EXISTS TBPERFILMESA;
DROP TABLE IF EXISTS TBMENUSUBITEMS;
DROP TABLE IF EXISTS TBMENUITEMS;
